name: "Theme Validation"
description: "Validate the themes"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
        cache-dependency-path: package-lock.json

    - name: install deps
      run: npm ci
      shell: bash

    - name: create generated dir
      run: mkdir ./assets/generated
      shell: bash

    - name: Prepare deploy
      run: npm run prepare-deploy
      shell: bash
