name: Theme Validation
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '10.x'
          
      - name: install deps
        run: npm install
          
      - name: Compile license info
        run: npm run generate:licenses
     
      - name: Compile and validate themes and layers
        run: npm run generate:layeroverview
